# Generated by Django 4.1.6 on 2023-03-09 20:13

import MedicalConvoyMangementSystem.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_messages_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='logo',
            field=models.ImageField(upload_to=MedicalConvoyMangementSystem.settings.get_upload_to),
        ),
        migrations.AlterField(
            model_name='home',
            name='poster_path',
            field=models.ImageField(upload_to=MedicalConvoyMangementSystem.settings.get_upload_to),
        ),
    ]
