# Generated by Django 4.1.6 on 2023-03-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_home_logo_alter_home_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='email',
        ),
        migrations.RemoveField(
            model_name='home',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='home',
            name='logo',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='poster_path',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='slogan',
            field=models.CharField(max_length=300),
        ),
    ]
