# Generated by Django 4.1.6 on 2023-03-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_home_email_remove_home_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='poster_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
