# Generated by Django 4.1.6 on 2023-03-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_home_logo_alter_home_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='home',
            name='poster_path',
        ),
    ]
