# Generated by Django 4.1.6 on 2023-03-10 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_home_logo_remove_home_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
